import { useId } from 'react';
import { getIllustration } from '../utils/illustrations';
import './CardHeader.css';

// ─── DESIGNER CONFIGURATION GUIDE ────────────────────────────────────────────
//
// CardHeader derives every visual property from the `theme` prop object.
// All themes originate from src/utils/themes.js.  To restyle a card header
// a designer edits that file only — no JSX changes required.
//
// ── REQUIRED THEME FIELDS ────────────────────────────────────────────────────
//
//   theme.name        {string}
//       Ticket title rendered in large bold type.
//       Keep under ~28 characters to avoid wrapping at 352 px card width.
//
//   theme.emoji       {string}
//       Single emoji displayed above the title.
//       Standard Unicode emoji recommended.  Custom glyphs require a
//       @font-face declaration added to CardHeader.css.
//
//   theme.price       {number}
//       Raw coin price — rendered as "{price}🪙" in the price badge.
//
//   theme.topPrize    {string}
//       Pre-formatted prize string (generated by fmtTopPrize in themes.js),
//       e.g. "10,000 COINS".  Displayed in the sub-title row.
//
//   theme.palette     {object}
//       Color system object — see palette fields below.
//
// ── PALETTE FIELDS CONSUMED BY CARDHEADER ────────────────────────────────────
//
//   palette.hdr       {[string, string, string]}
//       Three CSS color strings forming the header background gradient.
//       Index 0 = left edge, 1 = centre highlight, 2 = right edge.
//       Example: ['#8B6000', '#FFD700', '#8B6000']
//
//   palette.accent    {string}
//       Highlight color used for the TOP PRIZE text and the secondary
//       guilloche stroke.  Must contrast against the hdr gradient.
//
//   palette.border    {string}
//       Mid-tone color used for the primary guilloche stroke and the
//       subtle ribbon fill between the two curve layers.
//
// ── ILLUSTRATION LAYER — RENDER PROP ─────────────────────────────────────────
//
//   Pass `illustrationLayer` to inject a custom graphic behind all header
//   text.  It is called as a render function and mounted inside an
//   absolutely-positioned container covering the full header face.
//
//   Prop signature:
//     illustrationLayer(props: { width: number, height: string, palette: object })
//       → ReactNode
//
//   Minimal example:
//     <CardHeader
//       theme={theme}
//       illustrationLayer={({ palette }) => (
//         <img
//           src={myHeroAsset}
//           style={{ width:'100%', height:'100%', objectFit:'cover',
//                    opacity: 0.38, mixBlendMode: 'overlay' }}
//         />
//       )}
//     />
//
// ── ILLUSTRATION ASSET SPECIFICATION ─────────────────────────────────────────
//
//   Format
//     PNG-24 with alpha channel (preferred) or SVG with embedded imagery.
//     Avoid JPEG — loss artifacts become visible at overlay blend modes.
//
//   Pixel dimensions
//     Design target:  352 × 112 px  (card max-width × header min-height)
//     Retina (2×):    704 × 224 px  — required for all production handoff
//
//   Safe zones  (keep critical art out of these regions)
//     Left edge:    56 px  — price badge occupies this column
//     Right edge:   56 px  — reserved for visual symmetry
//     Bottom strip: 22 px  — guilloche border overlaps here; art will be
//                            partially obscured by the SVG curves
//
//   Blend mode recommendations by palette family
//     Light palettes (gold, green, orange, copper):
//         mixBlendMode: 'multiply',  opacity: 0.45
//     Dark palettes (navy, silver, purple, maroon):
//         mixBlendMode: 'screen',    opacity: 0.35
//     Universal safe default:
//         mixBlendMode: 'overlay',   opacity: 0.40
//
//   Color-reactive animation hooks
//     The render prop receives the live `palette` object on every render.
//     Map palette values to CSS custom properties to drive theme-responsive
//     animations without hardcoding colors in the illustration:
//
//       illustrationLayer={({ palette }) => (
//         <div
//           className="my-sprite"
//           style={{ '--glow': palette.accent, '--bg': palette.border }}
//         />
//       )}
//
//   CSS class hooks exposed on CardHeader DOM nodes
//     .card-header                 root wrapper — attach card-level animations
//     .card-header__illustration   illustration container — transition opacity here
//     .card-header__guilloche      the SVG border element — filter/opacity safe
//
// ─────────────────────────────────────────────────────────────────────────────


// ── Guilloche geometry constants ──────────────────────────────────────────────
//
// Adjust these to change the border's visual density without touching the
// component or its CSS.

/** Logical coordinate width — matches the card's max-width so the pattern
 *  fills edge-to-edge before SVG scaling is applied. */
const GW = 352;

/** Height of the guilloche band in logical pixels. */
const GH = 18;

/**
 * Builds SVG path strings for a three-layer mathematically generated
 * guilloche border.
 *
 * Algorithm
 * ─────────
 * Two counter-rotating sinusoidal curves are plotted at coprime frequency
 * ratios f1 and f2.  Because the frequencies share no common factor, the
 * phase relationship between the curves never exactly repeats within a
 * single parameter sweep, producing f1 × f2 structurally distinct enclosed
 * "lozenge" cells — the hallmark of engine-turned guilloche engraving on
 * physical banknotes and security documents.
 *
 * A third independent thread at prime frequency f3 runs through the centre
 * of the lozenge field, adding fine interior detail.
 *
 * The result is computed once at module-load time and shared across all
 * CardHeader instances (immutable constant — no per-render cost).
 *
 * Parameters chosen
 *   f1 = 7, f2 = 11  →  lcm(7,11) = 77 lozenge intersections per sweep
 *   f3 = 31           →  31 fine centre ripples (coprime with both f1, f2)
 *
 * @returns {{ upper: string, lower: string, center: string }}
 */
function buildGuilloche() {
  const STEPS = 480;          // sample count — 480 gives ~1.4 pts/px at GW=352
  const cy    = GH / 2;       // vertical centre of the band

  // Coprime frequency triplet — no two share a common factor.
  const f1 = 7, f2 = 11, f3 = 31;

  // Amplitude layers expressed as fractions of the half-band height (cy = 9px).
  const A = cy * 0.76;        // primary undulation  — approaches both edges
  const B = cy * 0.28;        // secondary modulation — interference ripple
  const C = cy * 0.10;        // tertiary detail      — fine centre thread

  // Phase offsets create asymmetric crossing angles, producing true lozenge
  // shapes rather than diamond-point intersections.
  const phi1 =  0.82;
  const phi2 = -0.82;

  const upper = [], lower = [], center = [];

  for (let i = 0; i <= STEPS; i++) {
    const t = (i / STEPS) * Math.PI * 2;   // parameter: 0 → 2π
    const x = (i / STEPS) * GW;

    // Upper curve: negative primary, positive secondary.
    // Tracks the "top" of each lozenge cell.
    const yu = cy - A * Math.sin(f1 * t) - B * Math.sin(f2 * t + phi1);
    upper.push(`${i === 0 ? 'M' : 'L'}${x.toFixed(2)},${yu.toFixed(2)}`);

    // Lower curve: positive primary (counter-rotation), phase-shifted secondary.
    // Crosses upper curve f1 times per sweep → encloses the lozenge cells.
    const yl = cy + A * Math.sin(f1 * t) + B * Math.sin(f2 * t + phi2);
    lower.push(`${i === 0 ? 'M' : 'L'}${x.toFixed(2)},${yl.toFixed(2)}`);

    // Centre thread: independent fine-frequency sinusoid.
    // Visible through the gaps between lozenges; adds micro-detail.
    const yc = cy + C * Math.sin(f3 * t + Math.PI * 0.33);
    center.push(`${i === 0 ? 'M' : 'L'}${x.toFixed(2)},${yc.toFixed(2)}`);
  }

  // Ribbon path: forward along upper, then backward along lower (pre-reversed),
  // closed with Z.  Used for the semi-transparent fill between curve layers.
  const lowerSegments = [];
  for (let i = STEPS; i >= 0; i--) {
    const t  = (i / STEPS) * Math.PI * 2;
    const x  = (i / STEPS) * GW;
    const yl = cy + A * Math.sin(f1 * t) + B * Math.sin(f2 * t + phi2);
    lowerSegments.push(`L${x.toFixed(2)},${yl.toFixed(2)}`);
  }

  return {
    upper:  upper.join(' '),
    lower:  lower.join(' '),
    ribbon: upper.join(' ') + ' ' + lowerSegments.join(' ') + ' Z',
    center: center.join(' '),
  };
}

// Computed once at module load — deterministic, shared across all instances.
const GP = buildGuilloche();


// ── Component ─────────────────────────────────────────────────────────────────

/**
 * CardHeader — standalone, reusable lottery ticket header.
 *
 * Props
 * ─────
 * theme             {object}    Required.  Full theme object from themes.js.
 * illustrationLayer {function}  Optional.  Render prop for designer artwork.
 *                               Called as illustrationLayer({ width, height, palette }).
 *                               See DESIGNER CONFIGURATION GUIDE above.
 */
export default function CardHeader({ theme, illustrationLayer = null }) {
  const { palette } = theme;

  // Unique id scoped to this instance — prevents <clipPath> id collisions
  // when multiple CardHeaders render simultaneously (e.g. the picker grid).
  const uid    = useId();
  const clipId = `ch-gc-${uid}`;

  const hdBg = `linear-gradient(135deg, ${palette.hdr[0]}, ${palette.hdr[1]}, ${palette.hdr[2]})`;

  // Auto-resolve illustration from theme id; explicit prop overrides.
  const resolvedLayer = illustrationLayer || getIllustration(theme.id);

  return (
    <div className="card-header" style={{ background: hdBg }}>

      {/* ── Illustration slot ─────────────────────────────────────────── */}
      {/* Rendered at z-index 0 — beneath price badge, title, and guilloche.
          Resolved from theme.id automatically; override via illustrationLayer prop.
          See DESIGNER CONFIGURATION GUIDE at the top of this file. */}
      {resolvedLayer && (
        <div className="card-header__illustration" aria-hidden="true">
          {resolvedLayer({ width: GW, height: '100%', palette })}
        </div>
      )}

      {/* ── Price badge ──────────────────────────────────────────────── */}
      <div className="card-header__price">
        {theme.price}🪙
      </div>

      {/* ── Emoji + name ─────────────────────────────────────────────── */}
      <div className="card-header__title">
        <span className="card-header__emoji" aria-hidden="true">{theme.emoji}</span>
        <span className="card-header__name">{theme.name}</span>
      </div>

      {/* ── Top prize line ───────────────────────────────────────────── */}
      <div className="card-header__top-prize" style={{ color: palette.accent }}>
        TOP PRIZE: {theme.topPrize}
      </div>

      {/* ── Guilloche border ─────────────────────────────────────────── */}
      {/* Three-layer SVG that visually separates the header from the play
          area below.  Replaces a simple CSS border-bottom.
          Layers (back to front):
            1. Shadow echoes    — depth / emboss illusion
            2. Ribbon fill      — semi-transparent area between curve pair
            3. Upper curve      — primary guilloche line (palette.border)
            4. Lower curve      — counter-rotating line (palette.accent)
            5. Centre thread    — fine detail through lozenge interiors
          The SVG <clipPath> is instance-scoped via useId() so the element
          renders correctly even when dozens of cards are on screen at once. */}
      <svg
        className="card-header__guilloche"
        viewBox={`0 0 ${GW} ${GH}`}
        preserveAspectRatio="none"
        aria-hidden="true"
      >
        <defs>
          <clipPath id={clipId}>
            <rect x="0" y="0" width={GW} height={GH} />
          </clipPath>
        </defs>

        {/* Layer 1: drop-shadow echoes — drawn first, behind everything */}
        <path d={GP.upper}  clip-path={`url(#${clipId})`} stroke="rgba(0,0,0,0.32)" strokeWidth="1.7" fill="none" transform="translate(0,0.8)" />
        <path d={GP.lower}  clip-path={`url(#${clipId})`} stroke="rgba(0,0,0,0.22)" strokeWidth="1.4" fill="none" transform="translate(0,0.6)" />

        {/* Layer 2: ribbon fill between the two main curves */}
        <path d={GP.ribbon} clip-path={`url(#${clipId})`} fill={palette.border} opacity="0.14" />

        {/* Layer 3: primary upper curve */}
        <path d={GP.upper}  clip-path={`url(#${clipId})`} stroke={palette.border} strokeWidth="1.1" fill="none" opacity="0.90" />

        {/* Layer 4: counter-rotating lower curve */}
        <path d={GP.lower}  clip-path={`url(#${clipId})`} stroke={palette.accent} strokeWidth="0.85" fill="none" opacity="0.75" />

        {/* Layer 5: fine centre thread */}
        <path d={GP.center} clip-path={`url(#${clipId})`} stroke="rgba(255,255,255,0.32)" strokeWidth="0.5" fill="none" />
      </svg>

    </div>
  );
}
